pipeline:
    name: CI
    identifier: CI
    projectIdentifier: pingpong
    orgIdentifier: default
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: GitHub_Connector
                build: <+input>
    stages:
        - stage:
              name: Build
              identifier: Build
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: k8sconnector
                          namespace: harness-delegate-ng
                          serviceAccountName: harness-delegate-sa
                          automountServiceAccountToken: true
                          nodeSelector: {}
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: Gradle Build
                                identifier: Gradle_Build
                                spec:
                                    connectorRef: DockerHub_Connector
                                    image: hridyanshu/java_ubuntu
                                    shell: Sh
                                    command: |-
                                        cd services/pingpong

                                        ./gradlew build
                                    privileged: true
                                    resources:
                                        limits:
                                            memory: 1G
                          - step:
                                type: BuildAndPushECR
                                name: Build and Push to ECR
                                identifier: Build_and_Push_to_ECR
                                spec:
                                    connectorRef: AWSconnector
                                    region: ap-south-1
                                    account: "150097413076"
                                    imageName: demo-harness-pipeline
                                    tags:
                                        - latest
                                    dockerfile: services/pingpong/src/main/resources/docker/Dockerfile
                                failureStrategies: []
