pipeline:
    name: Terraform-terragrunt
    identifier: Terraformterragrunt
    projectIdentifier: pingpong
    orgIdentifier: default
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: GitHub_Connect
                build: <+input>
    stages:
        - stage:
              name: Tf-init
              identifier: Tfinit
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: k8sconnector
                          namespace: harness-delegate-ng
                          volumes: []
                          serviceAccountName: harness-delegate-sa
                          automountServiceAccountToken: true
                          nodeSelector: {}
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: Terraform-init
                                identifier: Terraforminit
                                spec:
                                    connectorRef: DockerHub_Connector
                                    image: hridyanshu/terragrunt_custom:1
                                    shell: Sh
                                    command: |-
                                        cd dev/infra/01-vpc

                                        terraform init
        - stage:
              name: Tf-plan
              identifier: Tfapply
              type: CI
              spec:
                  cloneCodebase: false
                  infrastructure:
                      useFromStage: Tfinit
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: Terraform plan
                                identifier: Terraform_plan
                                spec:
                                    connectorRef: DockerHub_Connector
                                    image: hridyanshu/terragrunt_custom:1
                                    shell: Sh
                                    command: |-
                                        cd dev/infra/01-vpc

                                        terraform validate

                                        terraform plan
        - stage:
              name: Plan Approval
              identifier: Plan_Approval
              description: ""
              type: Approval
              spec:
                  execution:
                      steps:
                          - step:
                                name: Approval
                                identifier: approval
                                type: HarnessApproval
                                timeout: 1d
                                spec:
                                    approvalMessage: |-
                                        Please review the following information
                                        and approve the pipeline progression
                                    includePipelineExecutionHistory: true
                                    approvers:
                                        minimumCount: 1
                                        disallowPipelineExecutor: false
                                        userGroups:
                                            - account.Approvers
                                    approverInputs: []
              tags: {}
        - stage:
              name: Tf-apply
              identifier: Tfdeploy
              type: CI
              spec:
                  cloneCodebase: false
                  infrastructure:
                      useFromStage: Tfinit
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: Terraform apply
                                identifier: Terraform_apply
                                spec:
                                    connectorRef: DockerHub_Connector
                                    image: hridyanshu/terragrunt_custom:1
                                    shell: Sh
                                    command: |-
                                        cd dev/infra/01-vpc

                                        terraform init

                                        terraform apply --auto-approve
